// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCronJob(arg1, arg2) {
  return window['go']['backend']['Backend']['AddCronJob'](arg1, arg2);
}

export function Backup(arg1) {
  return window['go']['backend']['Backend']['Backup'](arg1);
}

export function CheckAdmin() {
  return window['go']['backend']['Backend']['CheckAdmin']();
}

export function CleanCachePackages() {
  return window['go']['backend']['Backend']['CleanCachePackages']();
}

export function CommandExists(arg1) {
  return window['go']['backend']['Backend']['CommandExists'](arg1);
}

export function CreateGroup(arg1, arg2) {
  return window['go']['backend']['Backend']['CreateGroup'](arg1, arg2);
}

export function CreateUser(arg1) {
  return window['go']['backend']['Backend']['CreateUser'](arg1);
}

export function DeleteGroup(arg1) {
  return window['go']['backend']['Backend']['DeleteGroup'](arg1);
}

export function DeleteTempFiles(arg1, arg2) {
  return window['go']['backend']['Backend']['DeleteTempFiles'](arg1, arg2);
}

export function DeleteUser(arg1, arg2, arg3) {
  return window['go']['backend']['Backend']['DeleteUser'](arg1, arg2, arg3);
}

export function DisableService(arg1) {
  return window['go']['backend']['Backend']['DisableService'](arg1);
}

export function DuplicatedFiles(arg1) {
  return window['go']['backend']['Backend']['DuplicatedFiles'](arg1);
}

export function EnableService(arg1) {
  return window['go']['backend']['Backend']['EnableService'](arg1);
}

export function ExportLogs(arg1, arg2, arg3) {
  return window['go']['backend']['Backend']['ExportLogs'](arg1, arg2, arg3);
}

export function GenerateKeys(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['Backend']['GenerateKeys'](arg1, arg2, arg3, arg4);
}

export function GenerateSelfSignedCertificate(arg1) {
  return window['go']['backend']['Backend']['GenerateSelfSignedCertificate'](arg1);
}

export function GetAllServices() {
  return window['go']['backend']['Backend']['GetAllServices']();
}

export function GetCPUUsage() {
  return window['go']['backend']['Backend']['GetCPUUsage']();
}

export function GetDiskUsage() {
  return window['go']['backend']['Backend']['GetDiskUsage']();
}

export function GetDistribution() {
  return window['go']['backend']['Backend']['GetDistribution']();
}

export function GetLSCPU() {
  return window['go']['backend']['Backend']['GetLSCPU']();
}

export function GetLogs(arg1, arg2) {
  return window['go']['backend']['Backend']['GetLogs'](arg1, arg2);
}

export function GetMemoryUsage() {
  return window['go']['backend']['Backend']['GetMemoryUsage']();
}

export function GetNetworkUsage() {
  return window['go']['backend']['Backend']['GetNetworkUsage']();
}

export function GetProcessInfo() {
  return window['go']['backend']['Backend']['GetProcessInfo']();
}

export function GetRunningServices() {
  return window['go']['backend']['Backend']['GetRunningServices']();
}

export function GetSystemInfo() {
  return window['go']['backend']['Backend']['GetSystemInfo']();
}

export function InstallPackage(arg1) {
  return window['go']['backend']['Backend']['InstallPackage'](arg1);
}

export function ListCronJobs() {
  return window['go']['backend']['Backend']['ListCronJobs']();
}

export function ListPackages() {
  return window['go']['backend']['Backend']['ListPackages']();
}

export function ModifyGroup(arg1, arg2) {
  return window['go']['backend']['Backend']['ModifyGroup'](arg1, arg2);
}

export function ModifyUser(arg1, arg2) {
  return window['go']['backend']['Backend']['ModifyUser'](arg1, arg2);
}

export function MonitorDir(arg1) {
  return window['go']['backend']['Backend']['MonitorDir'](arg1);
}

export function MonitorFile(arg1) {
  return window['go']['backend']['Backend']['MonitorFile'](arg1);
}

export function MonitorSystemStats(arg1) {
  return window['go']['backend']['Backend']['MonitorSystemStats'](arg1);
}

export function OpenDialogError(arg1) {
  return window['go']['backend']['Backend']['OpenDialogError'](arg1);
}

export function OpenDialogInfo(arg1) {
  return window['go']['backend']['Backend']['OpenDialogInfo'](arg1);
}

export function OpenDialogQuestion(arg1) {
  return window['go']['backend']['Backend']['OpenDialogQuestion'](arg1);
}

export function OpenDialogWarning(arg1) {
  return window['go']['backend']['Backend']['OpenDialogWarning'](arg1);
}

export function OpenDir() {
  return window['go']['backend']['Backend']['OpenDir']();
}

export function OpenFile() {
  return window['go']['backend']['Backend']['OpenFile']();
}

export function OpenURL(arg1) {
  return window['go']['backend']['Backend']['OpenURL'](arg1);
}

export function RemoveAllCronJobs() {
  return window['go']['backend']['Backend']['RemoveAllCronJobs']();
}

export function RemoveCronJob(arg1) {
  return window['go']['backend']['Backend']['RemoveCronJob'](arg1);
}

export function RemoveOldLogs(arg1) {
  return window['go']['backend']['Backend']['RemoveOldLogs'](arg1);
}

export function RemovePackage(arg1) {
  return window['go']['backend']['Backend']['RemovePackage'](arg1);
}

export function RemoveUnusedPackages() {
  return window['go']['backend']['Backend']['RemoveUnusedPackages']();
}

export function ScheduleBackup(arg1, arg2) {
  return window['go']['backend']['Backend']['ScheduleBackup'](arg1, arg2);
}

export function StartService(arg1) {
  return window['go']['backend']['Backend']['StartService'](arg1);
}

export function Startup(arg1) {
  return window['go']['backend']['Backend']['Startup'](arg1);
}

export function StopService(arg1) {
  return window['go']['backend']['Backend']['StopService'](arg1);
}

export function TerminateProcess(arg1) {
  return window['go']['backend']['Backend']['TerminateProcess'](arg1);
}

export function WatchList() {
  return window['go']['backend']['Backend']['WatchList']();
}
