// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCronJob(arg1, arg2) {
  return window['go']['backend']['Backend']['AddCronJob'](arg1, arg2);
}

export function AddFirewallRule(arg1) {
  return window['go']['backend']['Backend']['AddFirewallRule'](arg1);
}

export function Backup(arg1) {
  return window['go']['backend']['Backend']['Backup'](arg1);
}

export function CheckAdmin() {
  return window['go']['backend']['Backend']['CheckAdmin']();
}

export function CommandExists(arg1) {
  return window['go']['backend']['Backend']['CommandExists'](arg1);
}

export function CreateGroup(arg1, arg2) {
  return window['go']['backend']['Backend']['CreateGroup'](arg1, arg2);
}

export function CreateUser(arg1) {
  return window['go']['backend']['Backend']['CreateUser'](arg1);
}

export function DeleteGroup(arg1) {
  return window['go']['backend']['Backend']['DeleteGroup'](arg1);
}

export function DeleteUser(arg1, arg2, arg3) {
  return window['go']['backend']['Backend']['DeleteUser'](arg1, arg2, arg3);
}

export function ExportLogs(arg1, arg2) {
  return window['go']['backend']['Backend']['ExportLogs'](arg1, arg2);
}

export function GetCPUUsage() {
  return window['go']['backend']['Backend']['GetCPUUsage']();
}

export function GetDefaultPolicy(arg1) {
  return window['go']['backend']['Backend']['GetDefaultPolicy'](arg1);
}

export function GetDiskUsage() {
  return window['go']['backend']['Backend']['GetDiskUsage']();
}

export function GetDistribution() {
  return window['go']['backend']['Backend']['GetDistribution']();
}

export function GetFirewallStatus() {
  return window['go']['backend']['Backend']['GetFirewallStatus']();
}

export function GetLSCPU() {
  return window['go']['backend']['Backend']['GetLSCPU']();
}

export function GetLogs(arg1, arg2) {
  return window['go']['backend']['Backend']['GetLogs'](arg1, arg2);
}

export function GetMemoryUsage() {
  return window['go']['backend']['Backend']['GetMemoryUsage']();
}

export function GetNetworkInterfaces() {
  return window['go']['backend']['Backend']['GetNetworkInterfaces']();
}

export function GetNetworkUsage() {
  return window['go']['backend']['Backend']['GetNetworkUsage']();
}

export function GetProcessInfo() {
  return window['go']['backend']['Backend']['GetProcessInfo']();
}

export function GetSystemInfo() {
  return window['go']['backend']['Backend']['GetSystemInfo']();
}

export function InstallPackage(arg1) {
  return window['go']['backend']['Backend']['InstallPackage'](arg1);
}

export function ListCronJobs() {
  return window['go']['backend']['Backend']['ListCronJobs']();
}

export function ListFirewallRules() {
  return window['go']['backend']['Backend']['ListFirewallRules']();
}

export function ListPackages() {
  return window['go']['backend']['Backend']['ListPackages']();
}

export function ModifyGroup(arg1, arg2) {
  return window['go']['backend']['Backend']['ModifyGroup'](arg1, arg2);
}

export function ModifyUser(arg1, arg2) {
  return window['go']['backend']['Backend']['ModifyUser'](arg1, arg2);
}

export function RemoveAllCronJobs() {
  return window['go']['backend']['Backend']['RemoveAllCronJobs']();
}

export function RemoveCronJob(arg1) {
  return window['go']['backend']['Backend']['RemoveCronJob'](arg1);
}

export function RemoveFirewallRule(arg1) {
  return window['go']['backend']['Backend']['RemoveFirewallRule'](arg1);
}

export function RemovePackage(arg1) {
  return window['go']['backend']['Backend']['RemovePackage'](arg1);
}

export function SetDefaultPolicy(arg1, arg2) {
  return window['go']['backend']['Backend']['SetDefaultPolicy'](arg1, arg2);
}

export function SetFirewallStatus(arg1) {
  return window['go']['backend']['Backend']['SetFirewallStatus'](arg1);
}

export function SetInterfaceStatus(arg1, arg2) {
  return window['go']['backend']['Backend']['SetInterfaceStatus'](arg1, arg2);
}

export function TerminateProcess(arg1) {
  return window['go']['backend']['Backend']['TerminateProcess'](arg1);
}
