// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCronJob(arg1, arg2) {
  return window['go']['main']['App']['AddCronJob'](arg1, arg2);
}

export function AddFirewallRule(arg1) {
  return window['go']['main']['App']['AddFirewallRule'](arg1);
}

export function CheckAdmin() {
  return window['go']['main']['App']['CheckAdmin']();
}

export function CreateUser() {
  return window['go']['main']['App']['CreateUser']();
}

export function CreateUser2(arg1) {
  return window['go']['main']['App']['CreateUser2'](arg1);
}

export function CreateUserWithDir(arg1) {
  return window['go']['main']['App']['CreateUserWithDir'](arg1);
}

export function DeleteUser(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteUser'](arg1, arg2, arg3);
}

export function DeleteUserWithDir(arg1) {
  return window['go']['main']['App']['DeleteUserWithDir'](arg1);
}

export function GetCPUInfo() {
  return window['go']['main']['App']['GetCPUInfo']();
}

export function GetDistribution() {
  return window['go']['main']['App']['GetDistribution']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListCronJobs() {
  return window['go']['main']['App']['ListCronJobs']();
}

export function ListFirewallRules() {
  return window['go']['main']['App']['ListFirewallRules']();
}

export function ListPackages() {
  return window['go']['main']['App']['ListPackages']();
}

export function PrintUsers() {
  return window['go']['main']['App']['PrintUsers']();
}

export function RemoveAllCronJobs() {
  return window['go']['main']['App']['RemoveAllCronJobs']();
}

export function RemoveFirewallRule(arg1) {
  return window['go']['main']['App']['RemoveFirewallRule'](arg1);
}
