// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCronJob(arg1, arg2) {
  return window['go']['main']['App']['AddCronJob'](arg1, arg2);
}

export function AddFirewallRule(arg1) {
  return window['go']['main']['App']['AddFirewallRule'](arg1);
}

export function CheckAdmin() {
  return window['go']['main']['App']['CheckAdmin']();
}

export function CreateGroup(arg1, arg2) {
  return window['go']['main']['App']['CreateGroup'](arg1, arg2);
}

export function CreateUser(arg1) {
  return window['go']['main']['App']['CreateUser'](arg1);
}

export function DeleteGroup(arg1) {
  return window['go']['main']['App']['DeleteGroup'](arg1);
}

export function DeleteUser(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteUser'](arg1, arg2, arg3);
}

export function GetDistribution() {
  return window['go']['main']['App']['GetDistribution']();
}

export function GetLSCPU() {
  return window['go']['main']['App']['GetLSCPU']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InstallPackage(arg1) {
  return window['go']['main']['App']['InstallPackage'](arg1);
}

export function ListCronJobs() {
  return window['go']['main']['App']['ListCronJobs']();
}

export function ListFirewallRules() {
  return window['go']['main']['App']['ListFirewallRules']();
}

export function ListPackages() {
  return window['go']['main']['App']['ListPackages']();
}

export function ModifyGroup(arg1, arg2) {
  return window['go']['main']['App']['ModifyGroup'](arg1, arg2);
}

export function ModifyUser(arg1, arg2) {
  return window['go']['main']['App']['ModifyUser'](arg1, arg2);
}

export function RemoveAllCronJobs() {
  return window['go']['main']['App']['RemoveAllCronJobs']();
}

export function RemoveFirewallRule(arg1) {
  return window['go']['main']['App']['RemoveFirewallRule'](arg1);
}

export function RemovePackage(arg1) {
  return window['go']['main']['App']['RemovePackage'](arg1);
}
