// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAdmin():Promise<boolean>;

export function CreateUser():Promise<void>;

export function CreateUserWithDir(arg1:string):Promise<void>;

export function DeleteUser():Promise<void>;

export function DeleteUserWithDir(arg1:string):Promise<void>;

export function GetDistribution():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ListPackages():Promise<Array<string>>;

export function PrintUsers():Promise<void>;
