// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAdmin() {
  return window['go']['main']['App']['CheckAdmin']();
}

export function CreateUser() {
  return window['go']['main']['App']['CreateUser']();
}

export function CreateUserWithDir(arg1) {
  return window['go']['main']['App']['CreateUserWithDir'](arg1);
}

export function DeleteUser() {
  return window['go']['main']['App']['DeleteUser']();
}

export function DeleteUserWithDir(arg1) {
  return window['go']['main']['App']['DeleteUserWithDir'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function PrintUsers() {
  return window['go']['main']['App']['PrintUsers']();
}
